name: SS6PlayerForCpp for Windows

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: release build
      run: .\scripts\release_win.ps1 Release

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        path: buildwin
        retention-days: 0

